services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ticketing-frontend:latest
    container_name: ticketing-frontend-web
    ports:
      - "8081:80"
    restart: unless-stopped
