services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticketing_backend
    ports:
      - "8080:8000"
    env_file:
      - .env
    volumes:
       - .:/var/www/html
    
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ticketing
      DB_USERNAME: ticketing_user
      DB_PASSWORD: ticketing_password
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: ticketing_mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ticketing
      MYSQL_USER: ticketing_user
      MYSQL_PASSWORD: ticketing_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot_password"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data: